language: node_js
compiler:
  - clang
matrix:
  include:
    - name: "Linux (glibc) - Node 6"
      os: linux
      dist: xenial
      sudo: true
      language: node_js
      node_js: "6"
      env:
        - CC="/usr/local/clang-7.0.0/bin/clang"
        - CXX="/usr/local/clang-7.0.0/bin/clang++"
    - name: "Linux (glibc) - Node 8"
      os: linux
      dist: xenial
      sudo: false
      language: node_js
      node_js: "8"
      env:
        - CC="/usr/local/clang-7.0.0/bin/clang"
        - CXX="/usr/local/clang-7.0.0/bin/clang++"
    - name: "Linux (glibc) - Node 10"
      os: linux
      dist: xenial
      sudo: false
      language: node_js
      node_js: "10"
      env:
        - CC="/usr/local/clang-7.0.0/bin/clang"
        - CXX="/usr/local/clang-7.0.0/bin/clang++"
      # after_success:
      #   - npm install coveralls
      #   - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - name: "Linux (glibc) - Node 11"
      os: linux
      dist: xenial
      sudo: false
      language: node_js
      node_js: "11"
      env:
        - CC="/usr/local/clang-7.0.0/bin/clang"
        - CXX="/usr/local/clang-7.0.0/bin/clang++"      
    - name: "OS X - Node 6"
      os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "6"
    - name: "OS X - Node 8"
      os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
    - name: "OS X - Node 10"
      os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "10"
    - name: "OS X - Node 11"
      os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "11"

before_install:
  - echo $CC
  - clang -v
  - clang++ -v