language: node_js
compiler:
  - clang
matrix:
  include:
    - name: "Linux (glibc) - Node 8"
      os: linux
      dist: xenial
      sudo: true
      language: node_js
      node_js: "8"
      env:
        - CC="/usr/local/clang-7.0.0/bin/clang"
        - CXX="/usr/local/clang-7.0.0/bin/clang++"
    - name: "OS X - Node 8"
      os: osx
      language: node_js
      sudo: true

before_install:
  - echo $CC
  - clang -v
  - clang++ -v
install:
  - npm install
  - npm install sharp async image-palette image-pixels
# if: tag IS present