compiler:
  - gcc
matrix:
  include:
    - name: "Linux (glibc) - Node 6"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      dist: trusty
      sudo: true
      language: node_js
      node_js: "6"
before_install:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - gcc -v
  - g++ -v
    # - name: "Linux (glibc) - Node 8"
    #   os: linux
    #   dist: trusty
    #   sudo: false
    #   language: node_js
    #   node_js: "8"
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #   packages:
    #         - g++-7
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # - name: "Linux (glibc) - Node 10"
    #   os: linux
    #   dist: trusty
    #   sudo: false
    #   language: node_js
    #   node_js: "10"
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #   packages:
    #         - g++-7
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    #   after_success:
    #     - npm install coveralls
    #     - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    # - name: "Linux (glibc) - Node 11"
    #   os: linux
    #   dist: trusty
    #   sudo: false
    #   language: node_js
    #   node_js: "11"
    # - name: "OS X - Node 6"
    #   os: osx
    #   osx_image: xcode9.2
    #   language: node_js
    #   node_js: "6"
    # - name: "OS X - Node 8"
    #   os: osx
    #   osx_image: xcode9.2
    #   language: node_js
    #   node_js: "8"
    # - name: "OS X - Node 10"
    #   os: osx
    #   osx_image: xcode9.2
    #   language: node_js
    #   node_js: "10"
    # - name: "OS X - Node 11"
    #   os: osx
    #   osx_image: xcode9.2
    #   language: node_js
    #   node_js: "11"

