image:
- Visual Studio 2017
configuration:
- Release
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true
install:
    - ps: Install-Product node 8 x64
    - ps: node --version
    - cmd: git submodule update --init --recursive
    - cmd: npm install
build_script: 
  - npm run build
after_build:
  - ps: Get-ChildItem .\prebuilds\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test_script:
  - npm run test
cache: 
  - build
  - node_modules -> package.json