image:
- Visual Studio 2017
configuration:
- Release
platform:
- x64
environment:
  matrix:
    - nodejs_version: "8"
matrix:
  fast_finish: true
install:
    - ps: Install-Product node 8 x64
    - ps: node --version
    - cmd: git submodule update --init --recursive
    - cmd: npm install
build: off
test_script:
  - npm run test