os: Visual Studio 2015
version: "{build}"
build: off
platform: x64
environment:
  matrix:
  - nodejs_version: "8"
  - nodejs_version: "10"
  - nodejs_version: "11"
    BUILD_PREBUILDS: "1"
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@5
  - cmd: git submodule update --init --recursive
  - npm install
test_script:
  - npm test